# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost
  username: blog_app
  password:
  port: 5432

development:
  <<: *default
  database: blog_development
test:
  <<: *default
  database: blog_test
production:
  <<: *default
  database: blog_production
