default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost
  username: blog_app
  password:
  port: 5432

development:
  <<: *default
  database: blog_development
test:
  <<: *default
  database: blog_test
production:
  <<: *default
  database: blog_production
